apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-api
  namespace: data-ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-api
  template:
    metadata:
      labels:
        app: ingestion-api
    spec:
      containers:
        - name: api
          image: harbor.home.badre2dine.dev/trading_data_ingest/data-ingest-api:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: api-secrets  # Optional: add if needed
      imagePullSecrets:
        - name: harbor-creds
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-api
  namespace: data-ingestion
spec:
  selector:
    app: ingestion-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: streamer-manager
  namespace: data-ingestion
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "patch", "delete", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: streamer-manager-binding
  namespace: data-ingestion
subjects:
  - kind: ServiceAccount
    name: default
    namespace: data-ingestion
roleRef:
  kind: Role
  name: streamer-manager
  apiGroup: rbac.authorization.k8s.io