apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-monthly
  namespace: data-ingestion
spec:
  schedule: "0 * * * *"  # Every hour
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: update-monthly
              image: harbor.home.badre2dine.dev/trading_data_ingest/data-ingest-monthly-update:latest
              envFrom:
                - secretRef:
                    name: api-secrets  # Optional: add if needed
          imagePullSecrets:
            - name: harbor-creds