apiVersion: v1
kind: PersistentVolume
metadata:
  name: parquet-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/parquet
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker-2 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: parquet-pvc
  namespace: data-ingestion
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: parquet-pv
  storageClassName: ""