apiVersion: v1
kind: Secret
metadata:
  name: keda-rabbitmq-secret
  namespace: data-ingestion
type: Opaque
stringData:
  host: "amqp://rabbitmq-headless.namespace.svc.cluster.local" 
  username: "username"
  password: "password"
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-rabbitmq
  namespace: data-ingestion
spec:
  secretTargetRef:
    - parameter: host
      name: keda-rabbitmq-secret
      key: host
    - parameter: username
      name: keda-rabbitmq-secret
      key: username
    - parameter: password
      name: keda-rabbitmq-secret
      key: password
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: celery-worker-scaler
  namespace: data-ingestion
spec:
  scaleTargetRef:
    name: celery-worker
  minReplicaCount: 0
  maxReplicaCount: 5
  pollingInterval: 10
  cooldownPeriod: 180
  triggers:
    - type: rabbitmq
      metadata:
        protocol: amqp
        queueName: celery
        mode: QueueLength
        value: "1"
      authenticationRef:
        name: keda-trigger-auth-rabbitmq
