# .github/workflows/test-runner.yaml
name: ARC Runner Scale Set Test

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: [arc-runner-1]
    steps:
      - name: Time check
        run: |
          echo "RUNNER started at: $(date -u)"
      - name: Network test
        run: curl -I https://github.com
