name: Build and Push to Harbor

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: [arc-runner-1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and Push Docker API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./api/dockerfile
          push: true
          tags: ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.HARBOR_PROJECT }}/data-ingest-api:latest

      - name: Build and Push Docker Worker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./worker/dockerfile
          push: true
          tags: ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.HARBOR_PROJECT }}/data-ingest-worker:latest
      - name: Build and Push pair ticker streamer image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./pair-tick-streamer/dockerfile
          push: true
          tags: ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.HARBOR_PROJECT }}/data-ingest-streamer:latest
      - name: Build and Push monthly update image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./monthly-update/dockerfile
          push: true
          tags: ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.HARBOR_PROJECT }}/data-ingest-monthly-update:latest
